import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AsideProvider } from "./context/AsideContext";
import { FilterProvider } from "./context/FilterContext";

const manropeFont = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${manropeFont.variable} antialiased bg-Neutral-100 dark:bg-Neutral-900-d`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <FilterProvider>
            <AsideProvider>{children}</AsideProvider>
          </FilterProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
