import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AsideProvider } from "./context/AsideContext";
import { FilterProvider } from "./context/FilterContext";
import { ModalProvider } from "./context/ModalContext";
import { UserProvider } from "./context/UserContext";
import ToastCustom from "./components/toastCustom";
import { BookmarkProvider } from "./context/BookmarkContext";

const manropeFont = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Bookmark App",
  description: "Generated by bookmark app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${manropeFont.variable} antialiased bg-Neutral-100 dark:bg-Neutral-900-d`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <UserProvider>
            <FilterProvider>
              <AsideProvider>
                <BookmarkProvider>
                  <ModalProvider>{children}</ModalProvider>
                </BookmarkProvider>
                <ToastCustom />
              </AsideProvider>
            </FilterProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
